[workspace]
members = [
    "cli-word-counter",
    "data-processing",
    "priority-queue",
    "redis/client",
    "redis/server",
    "redis/commands",
    "sleep-sort",
    "zipffuck-interpreter",
]
resolver = "2"
