[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
commands = { version = "0.1.0", path = "../commands" }
serde = "1.0.190"
serde_json = "1.0.108"
tokio = { version = "1.33.0", features = ["full"] }
