[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
commands = { version = "0.1.0", path = "../commands" }
serde = { version = "1.0.190", features = ["derive"] }
serde_json = "1.0.108"
tokio = { version = "1.33.0", features = ["full"] }
